name: mad_ui
description: MadUI packages for wireframe flutter mobile application.
version: 0.0.1
homepage: https://madstudio.dev/packages/mad_ui


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/
  